apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spiderjs.fullname" . }}
  labels:
    {{- include "spiderjs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spiderjs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spiderjs.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["spiderjs"]
          args: ["server", "--config", "/app/config/config.yaml"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: ml-model-volume
              mountPath: /app/configs/ml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "spiderjs.fullname" . }}-config
        - name: ml-model-volume
          configMap:
            name: {{ include "spiderjs.fullname" . }}-ml-model
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 